In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression,Ridge, Lasso, ElasticNet
from sklearn.metrics import r2_score,mean_squared_error
from math import sqrt

In [1]:
# importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
df = pd.read_csv("C:\\Users\\user\\Desktop\\NEET DATA_ Analysis\\data_full_detailed.csv")
df

,Year,Region,Exam Center,Type of Scam,Number of Cases,Actions Taken,Average Marks,Topper Marks,Number of Toppers,Number of Successful Candidates,Number of Perfect Scores
0,2016,North,A,None,0,None,76,95,3,160,0
1,2016,South,B,None,0,None,78,96,4,170,0
2,2017,North,A,None,0,None,77,95,3,170,0
3,2017,South,B,None,0,None,79,97,4,180,0
4,2018,North,A,None,0,None,78,96,3,165,0
5,2018,South,B,None,0,None,80,98,5,185,0
6,2019,North,A,None,0,None,77,95,4,160,0
7,2019,South,B,None,0,None,79,97,5,175,0
8,2020,North,A,None,0,None,76,95,3,155,0
9,2020,South,B,None,0,None,78,98,4,180,0
10,2021,North,A,None,0,None,75,95,3,150,0
11,2021,South,B,None,0,None,80,98,2,200,0
12,2022,North,A,None,0,None,78,97,4,180,0
13,2022,South,B,None,0,None,79,99,3,190,0
14,2023,North,A,None,0,None,77,97,2,160,0
15,2023,South,B,None,0,None,79,99,3,190,0
16,2024,North,A,Paper Leak,10,Exams Cancelled,85,100,10,200,5
17,2024,South,B,None,0,None,81,99,8,205,2
18,2024,West,D,Paper Leak,12,Exams Cancelled,90,100,12,190,6
19,2024,East,C,None,0,None,79,98,5,185,1